### PR TITLE
SRF02 ultrasonic range finder plugin

### PR DESCRIPTION
**Pull request by chunter1**
Simple SRF02 ultrasonic range finder plugin for one sensor connected via I2C and set to default address.

### CODE REVIEW

**Comment by shadow974** [comment]
How did you connect the Sensor to the ESP? The Sensor works with 5V and the whole ESP ist only 3.3V. Did you use a level-shifter?

**Comment by chunter1** [comment]
Hi,
the sensor itself ist powered by 5V.
The SCL and SDA lines are pulled up by a 1k resistor to 3.3V.
Works well since approx. 80 hours - continously logging in FHEM.
Resolution is: 0,3432 mm
Measurements ofcourse show a temperature dependency since the sensor has no temperature sensor on-board for compensating the varying speed of sound.

What i am not sure is, if it is allowed to use the necessary long transmit->receive "delay(70);" in my measuring function.
There is a possibility to reduce this time dynamically by constantly polling the software revision register to determine when the sensor has finished the measurement.
However the worst case "delay" would be the same.

**Comment by shadow974** [comment]
Nice! This was the reason i bought the SRF01. Measuring my Diesel for heating and logging it to fhem :dancer: I think your solution is a better approach than my software-serial version..

**Comment by chunter1** [comment]
Don't think it's better, just the SRF02 is (finally) cheaper and we can use several sensors on one ESP (with updated code).

**Pull request merged**
